@baseUrl = http://localhost:3333

@authToken = 

# @name authenticate
POST /sessions
Content-Type: application/json

{
  "email": "admin@gmail.com.br",
  "password": "123456"
}

###

# @name list_batch
GET /batch?currentPage=1&perPage=20
Content-Type: application/json
Authorization: Bearer 

###

# @name create_batch
POST /batch
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Any Name",
}

###

# @name update_batch
PUT /batch/af91fca5-6bf7-425c-8c1c-b25cfa28099b
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Maisson Saraiva"
}

###

# @name delete_batch
DELETE /batch/af91fca5-6bf7-425c-8c1c-b25cfa28099b
Content-Type: application/json
Authorization: Bearer 

###

# @name get_batch
GET /batch/9b219b88-db1a-4df8-8cb4-c03e2e540b4f
Content-Type: application/json
Authorization: Bearer 
