@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

###

# @name list_process_dispute
GET {{baseUrl}}/process-dispute?currentPage=1&perPage=20
Content-Type: application/json
Authorization: Bearer 

###

# @name create_process_dispute
POST {{baseUrl}}/process-dispute
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Any Name",
}

###

# @name update_process_dispute
PUT {{baseUrl}}/process-dispute/af91fca5-6bf7-425c-8c1c-b25cfa28099b
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Maisson Saraiva"
}

###

# @name delete_process_dispute
DELETE {{baseUrl}}/process-dispute/af91fca5-6bf7-425c-8c1c-b25cfa28099b
Content-Type: application/json
Authorization: Bearer 

###

# @name get_process_dispute
GET {{baseUrl}}/process-dispute/9b219b88-db1a-4df8-8cb4-c03e2e540b4f
Content-Type: application/json
Authorization: Bearer 
