name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar e configurar pnpm
      - name: Install and setup pnpm
        run: |
          npm install -g pnpm
          pnpm --version

      # Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # Rodar testes
      - name: Run tests
        run: pnpm run test

      # Build do projeto
      - name: Build project
        run: pnpm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Inicializar e aplicar o Terraform
      - name: Terraform Init and Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve
